# Theme settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"

# Site setttings
# logo: "/images/varsha.png"
title: "Varsha Kulkarni"
description: "Errs Unravelled"
url: "https://varshakulkarni.dev"
date_format: "%-d %b %Y"
read_time: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
twitter:
  username: varshamkulkarni

# Pagination
paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

google_analytics: ""
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Collections
collections:

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/varshamkulkarni
    icon: fab fa-twitter
  - title: GitHub
    url: https://github.com/Varsha-Kulkarni
    icon: fab fa-github
  - title: LinkedIn
    url: https://www.linkedin.com/in/varshakulkarni131184
    icon: fab fa-linkedin
  - title: Stackoverflow
    url: https://stackoverflow.com/users/1169441
    icon: fab fa-stack-overflow
  - title: Feed
    url: feed.xml
    icon: fas fa-rss
